name: serenitree_hack
description: "A mental health app with medication tracking and therapy features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.9.0
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.10.6
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.1.0
  flutter_animate: ^4.3.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  animations: ^2.0.11
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

