name: serenitree_hack
description: "A mental health app with medication tracking and therapy features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_animate: ^4.3.0
  animations: ^2.0.8
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  xml: ^6.3.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
